import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from './comp/Navbar'
import Footer from './comp/Footer'
import kraken from './Img/kraken.png'

const inter = Inter({ subsets: ['latin'] })

export default function main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <Navbar />
        <div className='w-[1080px] mx-auto py-24'>
            <Image className='mx-auto pb-20' src={kraken} alt="" width={800} />
            <div className='w-[640px] mx-auto'>
              <h1 className='pb-4'>Kraken</h1>
              <p className='pb-16'>Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc malesuada leo orci, vulputate fermentum quam maximus quis. Quisque ac quam vestibulum eros aliquam mattis sed nec massa. In hac habitasse platea dictumst. Vivamus vitae tincidunt mauris. Nullam eget massa libero. Praesent ac justo at felis faucibus viverra id et ante. Sed feugiat viverra libero dictum lobortis. Nam elementum scelerisque turpis. Mauris ipsum nunc, feugiat nec mollis sed, egestas sit amet orci. Proin eu libero consequat lacus semper scelerisque vel id enim.

              Suspendisse maximus, ante in lobortis consectetur, nibh lorem porta odio, quis malesuada nisl sem vitae dui. Proin laoreet facilisis nibh nec ornare. Mauris tempor arcu vel est bibendum interdum. Nam feugiat dui ante, ut vestibulum mi maximus id. In hac habitasse platea dictumst. Fusce magna metus, consectetur eget feugiat ut, facilisis vitae risus. Etiam aliquam tortor at ligula congue, in finibus dui porttitor. Nam tempus nulla sit amet fringilla pellentesque.</p>
              <h2 className='pb-4'>kraken</h2>
              <p className='pb-16'>Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc malesuada leo orci, vulputate fermentum quam maximus quis. Quisque ac quam vestibulum eros aliquam mattis sed nec massa. In hac habitasse platea dictumst. Vivamus vitae tincidunt mauris. Nullam eget massa libero. Praesent ac justo at felis faucibus viverra id et ante. Sed feugiat viverra libero dictum lobortis. Nam elementum scelerisque turpis. Mauris ipsum nunc, feugiat nec mollis sed, egestas sit amet orci. Proin eu libero consequat lacus semper scelerisque vel id enim.

              Suspendisse maximus, ante in lobortis consectetur, nibh lorem porta odio, quis malesuada nisl sem vitae dui. Proin laoreet facilisis nibh nec ornare. Mauris tempor arcu vel est bibendum interdum. Nam feugiat dui ante, ut vestibulum mi maximus id. In hac habitasse platea dictumst. Fusce magna metus, consectetur eget feugiat ut, facilisis vitae risus. Etiam aliquam tortor at ligula congue, in finibus dui porttitor. Nam tempus nulla sit amet fringilla pellentesque.</p>
            </div>
        </div>
        <Footer />
      </main>
    </>
  )
}