import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './comp/Navbar'
import Footer from './comp/Footer'
import HowToBuyPar from './comp/HowToBuyPar'

// import React from 'react';
// import { useQuery } from '@apollo/client';

// import { gql } from '../api/gql';

// const Blog = gql(/* GraphQL */ `
// query blog {
//   blog(where: {id: "cle0gf5622jfm0cus2tp7225j"}) {
//     blogDescription
//     blogHeading
//     blogRichText {
//       text
//     }
//     id
//   }
// `);

// export default function BlogPage() {
//   // our query's result, data, is typed!
//   const { loading, data } = useQuery(
//     Blog,
//     // variables are also typed!
//     { variables: { id: "cle0gf5622jfm0cus2tp7225j" } }
//   );
//   return (
//     <div>
//       <h3>Available Inventory</h3>
//       {loading ? (
//         <p>Loading ...</p>
//       ) : (
//         <table>
//           <thead>
//             <tr>
//               <th>Model</th>
//               <th>Stock</th>
//             </tr>
//           </thead>
//           <tbody>
//             {data && data.blog.map(blog => (
//               <tr>
//                 <td>{blog.blogDescription}</td>
//               </tr>
//             ))}
//           </tbody>
//         </table>
//       )}
//     </div>
//   );
// }

export default function main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <Navbar />
        <HowToBuyPar />
        <Footer />
      </main>
    </>
  )
}
