import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './comp/Navbar'
import Home from './comp/Home'
import AboutPageHome from './comp/AboutPageHome'
import ParAboutHome from './comp/ParAboutHome'
import Footer from './comp/Footer'

// import { gql } from "@apollo/client";
// import client from "../apollo-client";

// export async function getStaticProps({ blogDescription, blog }: { blogDescription: string, blog: string }) {
//   const { data } = await client.query({
//     query: gql`
//     query blog {
//       blog(where: {id: "cle0gf5622jfm0cus2tp7225j"}) {
//         blogDescription
//         blogHeading
//         blogRichText {
//           text
//         }
//         id
//       }
//     }    
    
//     `,
//   });

//   return {
//     blogblogDescription: data.blog.blogDescription,
//     blog: data
//  }
// }

export default function main({}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <Navbar />
        {/* <div>
          {blog.map(() => (
            <div>
              <h3>{blog.blogDescription}</h3>
              <p>
                xd
              </p>
            </div>
          ))}
        </div> */}
        <Home />
        <AboutPageHome />
        <ParAboutHome />
        <Footer />
      </main>
    </>
  )
}
