import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from './comp/Navbar'
import Footer from './comp/Footer'
import Paragraph from './comp/Paragraph'
import ReviewGrid from './comp/ReviewGrid'

const inter = Inter({ subsets: ['latin'] })

export default function main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" /> 
        <link rel="preconnect" href="https://fonts.gstatic.com" /> 
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <Navbar />
        <div className='py-32'>
          <Paragraph title='Opurtnitn 1' content='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus congue lectus at fermentum pellentesque. Pellentesque ullamcorper, neque vel sagittis posuere, justo ex bibendum ligula, sed scelerisque mauris nulla eget lectus. Nullam ligula libero, aliquet eu tincidunt at, posuere molestie odio. Sed bibendum fermentum orci. Nam a nisl varius, molestie nisi quis, mattis nisi. Nullam sit amet nisl lobortis, pretium sem non, vehicula odio. Duis et semper metus. Nulla eget pretium nunc, non viverra dolor' />
        </div>
        <div className='w-[1080px] mx-auto text-center'>
          <div className='grid grid-cols-6 gap-6 border-solid border-black border-b font-semibold text-lg'>
            <div>Burza</div>
            <div>Poplatky obchod</div>
            <div>Poplatky výběr</div>
            <div>KYC</div>
            <div>Easy to use</div>
            <div>Last option</div>
          </div>
          <ReviewGrid img='/Kraken-Logo.png' c2='2' c3='3' c4='4' c5='5' c6='6'/>
          <ReviewGrid img='/Coinbase-Logo.wine.png' c2='2' c3='3' c4='4' c5='5' c6='6'/>
          <ReviewGrid img='/Binance-Vertical-Black-Logo.wine.png' c2='2' c3='3' c4='4' c5='5' c6='6'/>
          <ReviewGrid img='/Kraken-Logo.png' c2='2' c3='3' c4='4' c5='5' c6='6'/>
        </div>
        <Footer />
      </main>
    </>
  )
}
